# Project Information
site_name: PagerDuty Retrospectives Documentation
site_description: A collection of information about the PagerDuty retrospectives process and industry best practices. This guide will teach you how to build a culture that encourages retrospectives, the most important components to include in your retros, and how to conduct effective retrospective meetings.
site_author: PagerDuty, Inc.
site_url: https://retrospectives.pagerduty.com/

# Repository
repo_url: https://github.com/pagerduty/retrospectives-docs

# Copyright
copyright: 'Copyright &copy; PagerDuty, Inc.'

# Theme
theme:
  name: pagerduty
  title: 'Retrospectives'

# Contents
nav:
  - Home: 'index.md'
  - Getting Started: 'getting_started.md'
  - Planning The Retrospective: 'planning.md'
  - During The Retrospective: 'during.md'
  - After The Retrospective: 'after.md'
  - Training For The Facilitator: 'facilitator_training.md'
  - Next Steps: 'next_steps.md'
  - Additional Resources: 'resources.md'

# Analytics
google_analytics: ['UA-8759953-1', 'auto']

# Extensions
markdown_extensions:
  - toc:
      permalink: '#'
  - sane_lists:
  - admonition:
  - meta:
  - pymdownx.details:
  - pymdownx.extra:
  - pymdownx.mark:
  - pymdownx.tilde:
  - pymdownx.highlight:
  - pymdownx.superfences:
  - pymdownx.tabbed:

# Development URL, bind to local only.
dev_addr: '127.0.0.1:8000'

